### ISSUE TITLE
Bug: VRP env bug

### ISSUE THREAD

**Issue by kevin031060** [hubbs5/or-gym#15]
![Screenshot from 2021-06-03 16-58-03](https://user-images.githubusercontent.com/9042154/120617774-0350ec80-c48d-11eb-9946-7971e47853ec.png)
It should be:

self.order_dict[order_idx][‘Status’] == 1

['Status'] missed

**Comment by osarwar** [comment]
Thank you for pointing this out. It's been fixed!
