### ISSUE TITLE
News Vendor ** ?

### ISSUE THREAD

**Issue by ChrisKahrs** [hubbs5/or-gym#23]
In line 87 of newsvendor there is a multiplication of several items but it ends with a ** of self.lead_time.  I think that is wrong.  

        purchase_cost = excess_inventory * self.cost * order_qty * \
            self.gamma ** self.lead_time

Happy to do a fix and PR if someone else can verify that is incorrect.   Thanks!

**Comment by hubbs5** [comment]
Hello,

Gamma is a discount factor that's discounted exponentially by the lead time. While we didn't enforce it in the code gamma should always be in the range: 0 < gamma <= 1.

Please let us know if you have any other questions!
