### ISSUE TITLE
Feature Request: Update gym dependency

### ISSUE THREAD

**Issue by PhilippWillms** [hubbs5/or-gym#32]
Hello,
I would like to raise the request to underpin the needed gym version to at least 0.21.0. This would be in line with the currently supported ray 2.x version.

**Comment by mawbray** [comment]
Hi guys, 

Love your work with this repo. 
I am having trouble installing via pip at the moment, and wonder whether it might related to something similar in this issue. I attach the below for your info.  

![image](https://github.com/hubbs5/or-gym/assets/47567802/5c293596-ed10-44f7-84c0-c50012ea5f58)

Someone else I know has also replicated this problem. I wonder if you could have a look? 

All the best, 
Max
