### ISSUE TITLE
Bounded Knapsack init Failure

### ISSUE THREAD

**Issue by Callen-Shutts** [hubbs5/or-gym#4]
Right now the Bounded Knapsack env fails to intitilize as `self.N` is not defined and is used on the first line. You will probabl  have to define  `self.N`  as you cannot move the super up as it will call the reset function that depends on the vars you need to define.

**Comment by hubbs5** [comment]
Thanks for catching that (and sorry about the delay)!

Just made a fix in version 0.2.0: https://pypi.org/project/or-gym/0.2.0/
