### ISSUE TITLE
import or_gym not working

### ISSUE THREAD

**Issue by bazok100** [hubbs5/or-gym#5]
Hi,
I am trying to import the or_gym module after pip installation but I keep having ModuleNotFoundError: No module named 'or_gym'. I am not sure why. Any help will be appreciated.

**Comment by hdavid16** [comment]
@bazok100 if you run 'pip list' in a terminal is the package listed?

**Comment by bazok100** [comment]
Yes it is listed when I run 'pip list'

**Comment by bazok100** [comment]
It is working now. I am on Colab and had initially cloned and installed in my g-drive. I deleted and used pip install directly and it works fine. Thanks alot!
