### ISSUE TITLE
Using NetworkManagement environments with ray

### ISSUE THREAD

**Issue by andrewdcamp** [hubbs5/or-gym#8]
Hi, 
I am following the example in[ this blog post.](https://www.datahubbs.com/how-to-use-deep-reinforcement-learning-to-improve-your-supply-chain/)
When trying to register the NetworkManagement-v0 environemnt with `ray` I received `NotImplementedError: Environment NetworkManagement-v0 not recognized.` In this repo, it looks like the NetworkManagement-v0 and v1 environments are not available options in the `create_envs` function from `utils.py`. 

Is there a reason why these are unavailable or cannot be used with ray?

**Comment by hdavid16** [comment]
Hi @andrewdcamp, are you trying to use the supply network environment?

**Comment by andrewdcamp** [comment]
@hdavid16 Yes, the environment in `network_management.py`

**Comment by hdavid16** [comment]
@andrewdcamp you should be using Invmanagement-v1 as stated in the blog post. This will run the supply chain under lost sales. If you want backlogging, then you will use v0.

**Comment by hdavid16** [comment]
Oh I see what you are trying to do now. You want to use the general supply network environment. If this is not working then there is a bug in registering the environment on our side. I'll get that fixed tomorrow.

**Comment by andrewdcamp** [comment]
@hdavid16 Sorry, to clarify - I am following the steps in the blog post but trying to use NetworkManagement instead of InvManagement. NetworkManagement seems to be left out of the available choices of environments in `utils.py` and I was wondering if there was a reason or if it was a bug.

**Comment by hdavid16** [comment]
@andrewdcamp I have registered these envs now:

`InvManagement-v2` is the backlog version of the general supply network env
`InvManagement-v3` is the lost sales version of the general supply network env
